### ISSUE TITLE
Option for font face?

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#13]
Would be nice to specify your favorite programming font.

**Comment by Aerilius** [comment]
I'd prefer sane defaults over (GUI) configurability, that means inheriting the OS's UI font and the OS's programming font.

**Comment by Aerilius** [comment]
Since many programmers like customization and many source code editors offer this (maybe because Windows seems not to allow setting your favorite programming font as  OS-wide default), we could implement at least a non-GUI way to override the inherited font. 

- Add a key to settings for enabling font override and for selected font
- Add code to sync all html code elements' font with this setting (need to be careful in which component this should be implemented without hardcoding references to certain elements)
- Settings are stored in registry. Not sure whether to introduce rather a configuration file for manual editing (using both adds complexity, or maybe replace registry by config file).

**Comment by thomthom** [comment]
Simplest might be to use `Sketchup.read_default` and pass that to the dialog as it boots (or as param in the file URL). That and document the setting.

I have been playing around with Ace myself the last few days - for a "Snippet-Player". Was able to set the font.

```
this.editor.setOptions({
        fontFamily: "Fira Code; monospace",
        fontSize: "14pt"
      });
```

**Comment by Aerilius** [comment]
Yes, but there are more places (console output is not an ace editor, but a look-alike).
In the back-end I use read-default, so that is at the moment the registry or plist, if that is not too inconvenient to edit manually then I can leave it as it is.

**Comment by thomthom** [comment]
Yea, that's fine by me. It'd be a one-time set-and-forget on each machine (SU instance). Mentioning that in the GitHub README is enough for me. (Maybe useful in the extension description.)

It's a tool for developers after all. Sublime, VS Code all have you set settings via editing settings files. I see this to be no different.

**Comment by Aerilius** [comment]
Added in branch [feature_font_family](https://github.com/Aerilius/sketchup-console-plus/tree/feature_font_family) and merged to master.
