### ISSUE TITLE
RangeError - is not id value

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#9]
It appear that face highlighting isn't working. (using commit 0222cd9e534a09a526661099bf325256bbcb9c68)

![2017-09-25_14h40_49](https://user-images.githubusercontent.com/192418/30808752-99a6ff44-a1ff-11e7-829b-bd98f95a7129.png)

Not sure where it gets that ID from though.

![2017-09-25_14h42_24](https://user-images.githubusercontent.com/192418/30808792-c0cae16c-a1ff-11e7-9df8-4cfcce9fb219.png)

**Comment by Aerilius** [comment]
Changed version of Ruby 😏 ? 

1. Instead of returning `nil`, not found objects raise, so I'll add a rescue for RangeError.

2. In my first examination of the issue I thought the it happens because the newer garbage collector is faster to delete unused references, for example `Sketchup.active_model.entities.to_a` would return an array of references that is not saved to a variable, thus the contained objects would be garbage collected and their IDs already invalid when the user hovers the console log.

But your example assigns the object to the reference `face`, which is apparently not garbage-collected. Maybe the object id does not match (`inspect` does not give the object id, but a somewhat odd calculated string representation of it).

**Comment by thomthom** [comment]
Ruby 2.2 - no change there. Though I'm not sure what last working version was. Maybe 2.2 did change something. Or maybe something with 64bit IDs?

So you are pulling the IDs from inspect? Are you parsing the `.inspect` string and then reversing that hex value back to what should be the id?

**Comment by Aerilius** [comment]
Parsing inspect in the output is the only way, because we only have the output.
I was parsing on the JavaScript side (now I think I would fit better on the Ruby side):
`var id = parseInt(RegExp.$1) >> 1;`
Maybe it should be `parseInt(string, 16) >> 1`  or parseInt detects "0x".
https://stackoverflow.com/a/2818916

**Comment by thomthom** [comment]
Given a string `hex = '0x0001c42b2acc40'`, this Ruby line `hex.to_i(16) >> 1` yields `971024721440`

**Comment by Aerilius** [comment]
`>>1` gives different results in Ruby and JavaScript (after change to 64bit and HtmlDialog).
I'll move the conversion to the Ruby side.

**Comment by Aerilius** [comment]
This was caused due to a change in Bridge that exceptions are not anymore automatically caught and turned into promise rejections anymore (in that case unexpected errors would have gone unnoticed). 

However this exception (RangeError) was expected and should reject the promise. I added an explicit rescue block to reject the promise, which will then remove the hover link.
